version: "3.8"
name: test-backend
services:
  db-test:
    container_name: db-test
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildTransfer
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wildTransfer -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 15

  backend-test:
    container_name: backend-test
    build: ./server
    env_file:
      - ./test.env
    ports:
      - 4040:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=test
    command: yarn dev
    volumes:
      - ./server/src/:/app/src/
    depends_on:
      db-test:
        condition: service_healthy

volumes:
  postgres:
