const fileMap = [
  {
    id: 1,
    image: '../../assets/file.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'file',
  },
  {
    id: 2,
    image: '../../assets/pdf.png',
    name: 'pdf',
    subtitle: 'pdf',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'pdf',
  },
  {
    id: 3,
    image: '../../assets/file.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'pdf',
  },
  {
    id: 4,
    image: '../../assets/pdf.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'file',
  },
  {
    id: 5,
    image: '../../assets/file.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'file',
  },
  {
    id: 6,
    image: '../../assets/pdf.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'file',
  },
  {
    id: 7,
    image: '../../assets/file.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'file',
  },
  {
    id: 8,
    image: '../../assets/pdf.png',
    name: 'File',
    subtitle: 'File',
    description: 'File',
    route: 'File',
    day: 0,
    size: '10 mo',
    type: 'file',
  },
]

export default fileMap
